### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by nikvdree** [rubentalstra/bak-counter#18]
![DALL·E 2024-03-21 09 05 57 - a sleek and modern logo design featuring the text 'BAK' in bold, stylized lettering, with a minimalist icon of a beer next to it  The design should be](https://github.com/rubentalstra/bak-counter/assets/33282605/6a03e74a-546f-48d0-a2bc-3ccce611739e)

**Comment by nikvdree** [comment]
['#b6ad9f', '#fefefe', '#202931', '#7f6a4f', '#9b9285']

**Comment by rubentalstra** [comment]
https://github.com/rubentalstra/bak-counter/pull/20
