### ISSUE TITLE
Weddenschappen door tegenstander laten accepteren

### ISSUE THREAD

**Issue by jasperreinders** [rubentalstra/bak-counter#27]
Voordat de weddenschap bij actieve weddenschappen staat, eerst laten accepteren door de tegenstander. Zo voorkom je ook het probleem dat mensen voor de grap weddenschappen tegen anderen erin gaan zetten.

**Comment by rubentalstra** [comment]
https://github.com/rubentalstra/bak-counter/pull/38/commits/2634709a910c7c61d5acf045ef9c55db9d06510a
