### ISSUE TITLE
Badges laten maken voor de XP levels en REP levels

### ISSUE THREAD

**Issue by rubentalstra** [rubentalstra/bak-counter#46]

**Comment by sander1946** [comment]
@rubentalstra wat vind je van deze badges voor de XP levels, ook in deze volgorde
![normal](https://github.com/rubentalstra/bak-counter/assets/71840186/ae973e76-1c8d-4496-89d8-5dd0c5f70b74)
![gray badge](https://github.com/rubentalstra/bak-counter/assets/71840186/461a9a40-7362-4de3-a027-f2d48e3c3bd7)
![bronze badge](https://github.com/rubentalstra/bak-counter/assets/71840186/c97859aa-63d8-44f8-b400-ad5c5ec161dc)
![zilver badge](https://github.com/rubentalstra/bak-counter/assets/71840186/ebc60130-bf87-489b-9a3c-2e48a2741812)
![gold badge](https://github.com/rubentalstra/bak-counter/assets/71840186/d0c37809-b8a5-47aa-810c-161a80e9face)

**Comment by rubentalstra** [comment]
Ziet er wel lijp uit. Deze is dan alleen voor de XP levels 🫡

**Comment by rubentalstra** [comment]
![Klootzak](https://github.com/rubentalstra/bak-counter/assets/14235001/f0da92d8-842e-4a0a-b3b3-a6ef35bee2c8)
![Schoft](https://github.com/rubentalstra/bak-counter/assets/14235001/4e429abb-5ea5-4c04-b283-3ea59c1dceec)
