### ISSUE TITLE
Tweede keer klikken op approve redirect naar een admin pagina

### ISSUE THREAD

**Issue by TomDarkVirus** [rubentalstra/bak-counter#6]
Als er op de approve knop geklikt wordt als 2e persoon wordt er geredirect naar een pagina die 'An admin must approve this request.' teruggeeft.

**Comment by rubentalstra** [comment]
als het goed is heb ik dit nu gefixed. zou je dit nog eens willen testen 😄

**Comment by TomDarkVirus** [comment]
Yes, kan nu niet meer op approve klikken als 2e
