### ISSUE TITLE
Kan voor andere mensen een challenge maken d.m.v. Burp

### ISSUE THREAD

**Issue by ThomasMLdeJong** [rubentalstra/bak-counter#8]
Titel spreekt voor zich
Hier is de payload

initiatorUserId=4&opponentUserId=5&judgeUserId=1&betTitle=Cringe&betDescription=Cringe&stake=1000000

**Comment by lunadude3** [comment]
Je kan ook de judge aanpassen naar jezelf. Hierdoor kan je dus heel makkelijk jezelf extreem veel rep geven en een ander extreem veel bakken
